stages:
    - build
docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  before_script:
    - ./bin/build
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  # Default branch leaves tag empty (= latest tag)
  # All other branches are tagged with the escaped branch name (commit ref slug)
  script:
    - docker build -t hub-peerxp.vegaops.com/devops-assignment/java_270422_6420 .
    - docker push "$CI_REGISTRY_IMAGE$"
